# Generated by Django 6.0.1 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="client_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(fields=("user", "client_id"), name="uniq_note_client_per_user"),
        ),
    ]
