# Generated by Django 6.0.1 on 2026-02-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_shareinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharelink',
            new_name='sharing_sha_resourc_3542e7_idx',
            old_name='sharing_sh_resource_4f0b96_idx',
        ),
    ]
