# Generated by Django 6.0.1 on 2026-02-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0003_rename_sharing_sh_resource_4f0b96_idx_sharing_sha_resourc_3542e7_idx"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="task",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.task"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="resource_type",
            field=models.CharField(choices=[("chat", "Chat"), ("note", "Note"), ("task", "Task")], max_length=12),
        ),
    ]

